server:
  port: 8080
spring:
  application:
    name: projeto-spring-mvc
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./banco/h2db_banco
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update